version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/solidity-splitter

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python3 -m unittest discover
